### ISSUE TITLE
不能成功运行python test.naive_bayes_test.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [geekhuyang/python-data-mining-platform#3]
```
What steps will reproduce the problem?
1. 直接到cd相应的目录，python test.naive_bayes_test.py

What is the expected output? What do you see instead?
实际看到的
Traceback (most recent call last):
  File "test.naive_bayes_test.py", line 11, in <module>
    PyMining.Init(config, "__global__", True
  File "D:\机器学习\pymining_0_1\py_mining.py", line 43, in Init
    PyMining.__ReadDict(PyMining.termToId, PyMining.nameTermToId, "str", "int")
  File "D:\机器学习\pymining_0_1\py_mining.py", line 65, in __ReadDict
    f = open(filename, "r")
IOError: [Errno 2] No such file or directory: u'mining/term_to_id'


What version of the product are you using? On what operating system?
win7，PyMining_0_1

Please provide any additional information below.


```

Original issue reported on code.google.com by `tianhong...@gmail.com` on 13 Apr 2012 at 12:48

**Comment by GoogleCodeExporter** [comment]
```
解决了，因为我loadfromfile但又没有对应文件，没有对应的文��
�时用false
```

Original comment by `tianhong...@gmail.com` on 13 Apr 2012 at 12:56

**Comment by GoogleCodeExporter** [comment]
```
我是新手。同样出现了no such file or directory
看了帖子之后，灵感突现。明白了错在哪里。
我的程序运行目录和所操作的文件目录不是同一个目录。只��
�把open()函数的filename前加上所操作文件所在目录就OK了。
```

Original comment by `friendly...@gmail.com` on 9 Jul 2012 at 3:49

**Comment by GoogleCodeExporter** [comment]
```
Traceback (most recent call last):
  File "naive_bayes_test.py", line 11, in <module>
    PyMining.Init(config, "__global__", True)
  File "/home/zhuajiayong/code_myself/search_engine/trunk/py_mining.py", line 38, in Init
    PyMining.__ReadDict(PyMining.termToId, PyMining.nameTermToId, "str", "int")
  File "/home/zhuajiayong/code_myself/search_engine/trunk/py_mining.py", line 60, in __ReadDict
    f = open(currentdir + filename, "r")
IOError: [Errno 2] No such file or directory: 
u'~/code_myself/search_engine/trunk/mining/mining/term_to_id'


我加了目录好像还是不行， 我的loadfromfile是false
```

Original comment by `jiayongb...@gmail.com` on 10 Dec 2012 at 9:15

**Comment by GoogleCodeExporter** [comment]
```
我的怎么加载了，也不能运行啊，，，

>>> 
config=Configuration.FromFile("D:\python\py_mining_0_2_D\example\conf\test.xml")

Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    config=Configuration.FromFile("D:\python\py_mining_0_2_D\example\conf\test.xml")
  File "D:\python\py_mining_0_2_D\pymining\common\configuration.py", line 34, in FromFile
    return Configuration(minidom.parse(path).childNodes[0])
  File "C:\Python27\lib\xml\dom\minidom.py", line 1914, in parse
    return expatbuilder.parse(file)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 922, in parse
    fp = open(file, 'rb')
IOError: [Errno 22] invalid mode ('rb') or filename: 
'D:\\python\\py_mining_0_2_D\\example\\conf\test.xml'
```

Original comment by `zhangjia...@gmail.com` on 4 May 2013 at 7:16

**Comment by GoogleCodeExporter** [comment]
```
不错，怎么不更新了
```

Original comment by `flysmart...@gmail.com` on 8 Nov 2014 at 5:51
